# Generated by Django 2.0.4 on 2018-08-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('cognome', models.CharField(blank=True, max_length=50)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('servizio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('note', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'contatti',
                'ordering': ['servizio'],
            },
        ),
    ]
