# Generated by Django 2.0.4 on 2018-04-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0007_delete_attivi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attivo',
            options={'ordering': ['cognome', '-attivo'], 'verbose_name_plural': 'utenti'},
        ),
    ]
