# Generated by Django 2.0.4 on 2018-05-08 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispositivi', '0019_auto_20180427_0929'),
        ('anagrafica', '0008_auto_20180424_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestiti_Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(choices=[('Roma - Laurentina', 'Roma - Laurentina'), ('Roma - Mattei', 'Roma - Mattei'), ('Milano - SDM', 'Milano - SDM')], default=('Roma - Laurentina', 'Roma - Laurentina'), max_length=30)),
                ('palazzo', models.CharField(blank=True, max_length=20, null=True)),
                ('piano', models.CharField(blank=True, max_length=10, null=True)),
                ('stanza', models.CharField(blank=True, max_length=3, null=True)),
                ('seriale', models.CharField(max_length=30, unique=True)),
                ('data_installazione', models.DateField()),
                ('data_dismissione', models.DateField(blank=True, null=True)),
                ('fine_garanzia', models.DateField(blank=True, null=True)),
                ('os', models.CharField(blank=True, max_length=15, null=True, verbose_name='O.S')),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
                ('modello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivi.Modello', verbose_name='modello')),
                ('produttore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivi.Produttore', verbose_name='produttore')),
                ('tipo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivi.Tipo_Dispositivo', verbose_name='tipo dispositivo')),
                ('attivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafica.Utente', verbose_name='assegnatario')),
            ],
            options={
                'verbose_name_plural': 'dispositivi',
            },
        ),
        migrations.CreateModel(
            name='Prestiti_Modello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modello', models.CharField(max_length=30, unique=True)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'modello',
                'verbose_name_plural': 'modelli',
                'ordering': ['modello'],
            },
        ),
        migrations.CreateModel(
            name='Prestiti_Produttore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produttore', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'produttore',
                'verbose_name_plural': 'produttori',
                'ordering': ['produttore'],
            },
        ),
        migrations.CreateModel(
            name='Prestiti_Tipo_Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dispositivo', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'dispositivo',
                'verbose_name_plural': 'tipi dispositivo',
                'ordering': ['tipo_dispositivo'],
            },
        ),
        migrations.CreateModel(
            name='Prestito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inizio_prestito', models.DateTimeField()),
                ('fine_prestito', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=300, null=True)),
                ('fk_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestiti.Prestiti_Dispositivo', verbose_name='dispositivo')),
                ('fk_utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafica.Utente', verbose_name='assegnatario')),
                ('tecnico_consegna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnico_consegna', to=settings.AUTH_USER_MODEL)),
                ('tecnico_ritiro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tecnico_ritiro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prestito',
                'verbose_name_plural': 'prestiti',
                'ordering': ['inizio_prestito'],
            },
        ),
        migrations.AddField(
            model_name='prestiti_modello',
            name='fk_produttore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestiti.Prestiti_Produttore', verbose_name='produttore'),
        ),
        migrations.AddField(
            model_name='prestiti_modello',
            name='fk_tipo_dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestiti.Prestiti_Tipo_Dispositivo', verbose_name='tipo dispositivo'),
        ),
    ]
