# Generated by Django 2.0.4 on 2018-05-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestiti', '0002_auto_20180508_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestiti_dispositivo',
            old_name='data_installazione',
            new_name='data_checkin',
        ),
        migrations.RenameField(
            model_name='prestiti_dispositivo',
            old_name='data_dismissione',
            new_name='data_checkout',
        ),
        migrations.RemoveField(
            model_name='prestiti_dispositivo',
            name='location',
        ),
        migrations.RemoveField(
            model_name='prestiti_dispositivo',
            name='palazzo',
        ),
        migrations.RemoveField(
            model_name='prestiti_dispositivo',
            name='piano',
        ),
        migrations.RemoveField(
            model_name='prestiti_dispositivo',
            name='stanza',
        ),
    ]
