# Generated by Django 2.0.4 on 2018-05-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestiti', '0007_prestiti_allegato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestiti_allegato',
            name='dispositivo',
        ),
        migrations.AddField(
            model_name='prestiti_allegato',
            name='prestito',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='prestiti.Prestito'),
            preserve_default=False,
        ),
    ]
