# Generated by Django 2.0.4 on 2018-05-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestiti', '0008_auto_20180515_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestiti_dispositivo',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
