# Generated by Django 2.0.4 on 2018-05-25 13:10

from django.db import migrations, models
import prestiti.models


class Migration(migrations.Migration):

    dependencies = [
        ('prestiti', '0010_auto_20180524_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestiti_dispositivo',
            name='data_checkin',
            field=models.DateField(validators=[prestiti.models.valida_data_checkin]),
        ),
        migrations.AlterField(
            model_name='prestiti_dispositivo',
            name='data_checkout',
            field=models.DateField(blank=True, null=True, validators=[prestiti.models.valida_data_checkout]),
        ),
        migrations.AlterField(
            model_name='prestiti_dispositivo',
            name='fine_garanzia',
            field=models.DateField(blank=True, null=True, validators=[prestiti.models.valida_fine_garanzia]),
        ),
    ]
