# Generated by Django 2.0.4 on 2018-06-04 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestiti', '0013_auto_20180528_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestito',
            name='fk_utente',
            field=models.ForeignKey(limit_choices_to={'attivo': 1}, on_delete=django.db.models.deletion.CASCADE, to='anagrafica.Utente', verbose_name='assegnatario'),
        ),
    ]
