# Generated by Django 2.0.4 on 2018-05-09 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestiti', '0004_auto_20180508_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestiti_dispositivo',
            name='utente',
        ),
    ]
