# Generated by Django 2.0.4 on 2018-05-11 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestiti', '0005_remove_prestiti_dispositivo_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestito',
            name='tecnico_ritiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tecnico_ritiro', to=settings.AUTH_USER_MODEL),
        ),
    ]
