# Generated by Django 2.0.4 on 2018-05-15 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestiti', '0006_auto_20180511_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestiti_Allegato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(blank=True, max_length=30, null=True)),
                ('allegato', models.FileField(upload_to='')),
                ('inserito_il', models.DateField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestiti.Prestiti_Dispositivo')),
            ],
            options={
                'verbose_name': 'allegato',
                'verbose_name_plural': 'allegati',
            },
        ),
    ]
