# Generated by Django 2.0.4 on 2018-05-25 14:31

from django.db import migrations, models
import prestiti.models


class Migration(migrations.Migration):

    dependencies = [
        ('prestiti', '0011_auto_20180525_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestito',
            name='fine_prestito',
            field=models.DateTimeField(blank=True, null=True, validators=[prestiti.models.valida_fine_prestito]),
        ),
        migrations.AlterField(
            model_name='prestito',
            name='inizio_prestito',
            field=models.DateTimeField(validators=[prestiti.models.valida_inizio_prestito]),
        ),
    ]
