# Generated by Django 2.0.4 on 2018-05-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestiti', '0012_auto_20180525_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestito',
            name='fine_prestito',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestito',
            name='inizio_prestito',
            field=models.DateTimeField(),
        ),
    ]
