# Generated by Django 2.0.4 on 2018-04-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervento',
            name='area_intervento',
            field=models.CharField(choices=[('use', 'User Management'), ('pcs', 'PC SW'), ('pch', 'PC HW'), ('mob', 'Mobile'), ('mes', 'Messaging'), ('vid', 'Video/Audio comunicazione'), ('con', 'Aree condivise'), ('bac', 'Backup/ripristino'), ('app', 'Applicativi'), ('sic', 'Sicurezza'), ('inf', 'Informazioni/procedure'), ('pri', 'Printing'), ('mov', 'Move')], max_length=3),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='numero_ticket',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='richiedente',
            field=models.CharField(default='ROSSELLA MACCHI', max_length=20),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='stato_intervento',
            field=models.CharField(choices=[('chi', 'chiuso'), ('cou', 'counter stop'), ('can', 'cancelled')], max_length=3),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='tipo_ingaggio',
            field=models.CharField(choices=[('mai', 'mail Coppetta'), ('tel', 'telefonata Coppetta')], max_length=3),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='tipo_ticket',
            field=models.CharField(choices=[('inc', 'incident'), ('ima', 'IMAC'), ('cha', 'change'), ('mov', 'move'), ('alt', 'altro')], max_length=3),
        ),
    ]
