# Generated by Django 2.0.4 on 2018-04-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0003_auto_20180424_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervento',
            name='tecnico',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
