# Generated by Django 2.0.4 on 2018-04-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0004_auto_20180424_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervento',
            name='descrizione_richiesta',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='note',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='numero_ticket',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='soluzione_adottata',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='tecnico',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
