# Generated by Django 2.0.4 on 2018-04-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0006_auto_20180424_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervento',
            name='data_chiusura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
