# Generated by Django 2.0.4 on 2018-04-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0007_intervento_data_chiusura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervento',
            name='area_intervento',
            field=models.CharField(choices=[('User Management', 'User Management'), ('PC SW', 'PC SW'), ('PC HW', 'PC HW'), ('Mobile', 'Mobile'), ('Messaging', 'Messaging'), ('Video/Audio comunicazione', 'Video/Audio comunicazione'), ('Aree condivise', 'Aree condivise'), ('Backup/ripristino', 'Backup/ripristino'), ('Applicativi', 'Applicativi'), ('Sicurezza', 'Sicurezza'), ('Informazioni/procedure', 'Informazioni/procedure'), ('Printing', 'Printing'), ('Move', 'Move')], max_length=30),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='stato_intervento',
            field=models.CharField(choices=[('chiuso', 'chiuso'), ('counter stop', 'counter stop'), ('cancelled', 'cancelled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='tipo_ingaggio',
            field=models.CharField(choices=[('mail Coppetta', 'mail Coppetta'), ('telefonata Coppetta', 'telefonata Coppetta')], max_length=30),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='tipo_ticket',
            field=models.CharField(choices=[('incident', 'incident'), ('IMAC', 'IMAC'), ('change', 'change'), ('move', 'move'), ('altro', 'altro')], max_length=30),
        ),
    ]
