# Generated by Django 2.0.4 on 2018-04-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivi', '0014_auto_20180420_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modello',
            name='modello',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='produttore',
            name='produttore',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo_dispositivo',
            name='tipo_dispositivo',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
