# Generated by Django 2.0.4 on 2018-04-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivi', '0015_auto_20180420_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='allegati',
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='os',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='O.S'),
        ),
    ]
