# Generated by Django 2.0.4 on 2018-04-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivi', '0016_auto_20180420_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='location',
            field=models.CharField(choices=[('lau', 'Roma - Laurentina'), ('mat', 'Roma - Mattei'), ('mat', 'Roma - Mattei')], default=('lau', 'Roma - Laurentina'), max_length=3),
        ),
    ]
