# Generated by Django 2.0.4 on 2018-05-25 09:39

import dispositivi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivi', '0019_auto_20180427_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='data_dismissione',
            field=models.DateField(blank=True, null=True, validators=[dispositivi.models.valida_data_dismissione]),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='data_installazione',
            field=models.DateField(validators=[dispositivi.models.valida_data_installazione]),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='fine_garanzia',
            field=models.DateField(blank=True, null=True, validators=[dispositivi.models.valida_fine_garanzia]),
        ),
    ]
