# Generated by Django 2.0.4 on 2018-05-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivi', '0021_auto_20180525_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='data_installazione',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='fine_garanzia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
