# Generated by Django 2.0.4 on 2018-04-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivi', '0017_auto_20180423_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='location',
            field=models.CharField(choices=[('lau', 'Roma - Laurentina'), ('mat', 'Roma - Mattei'), ('sdm', 'Milano - SDM')], default=('lau', 'Roma - Laurentina'), max_length=3),
        ),
    ]
