# Generated by Django 2.0.4 on 2018-05-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivi', '0020_auto_20180525_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='data_dismissione',
            field=models.DateField(blank=True, null=True),
        ),
    ]
