# Generated by Django 2.0.4 on 2018-04-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0007_delete_attivi'),
        ('dispositivi', '0018_auto_20180423_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(max_length=40)),
                ('tipo_servizio', models.CharField(default='ENHANCED', max_length=20)),
                ('richiedente', models.CharField(default='MACCHI', max_length=20)),
                ('data_richiesta', models.DateField()),
                ('tipo_ticket', models.CharField(choices=[('inc', 'incident'), ('ima', 'IMAC'), ('cha', 'change'), ('mov', 'move'), ('alt', 'altro')], default=('inc', 'incident'), max_length=3)),
                ('numero_ticket', models.CharField(max_length=10)),
                ('area_intervento', models.CharField(choices=[('use', 'User Management'), ('pcs', 'PC SW'), ('pch', 'PC HW'), ('mob', 'Mobile'), ('mes', 'Messaging'), ('vid', 'Video/Audio comunicazione'), ('con', 'Aree condivise'), ('bac', 'Backup/ripristino'), ('app', 'Applicativi'), ('sic', 'Sicurezza'), ('inf', 'Informazioni/procedure'), ('pri', 'Printing'), ('mov', 'Move')], default=('use', 'User Management'), max_length=3)),
                ('descrizione_richiesta', models.TextField(max_length=300)),
                ('soluzione_adottata', models.TextField(blank=True, max_length=300, null=True)),
                ('stato_intervento', models.CharField(choices=[('chi', 'chiuso'), ('cou', 'counter stop'), ('can', 'cancelled')], default=('chi', 'chiuso'), max_length=3)),
                ('tipo_ingaggio', models.CharField(choices=[('mai', 'mail Coppetta'), ('tel', 'telefonata Coppetta')], default=('mai', 'mail Coppetta'), max_length=3)),
                ('note', models.TextField(blank=True, max_length=300, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivi.Dispositivo', verbose_name='dispositivo')),
                ('fk_beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafica.Utente', verbose_name='beneficiario')),
            ],
            options={
                'verbose_name_plural': 'interventi',
            },
        ),
    ]
