# Generated by Django 2.0.4 on 2018-04-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0008_auto_20180426_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervento',
            name='data_chiusura',
            field=models.DateField(),
        ),
    ]
