# Generated by Django 2.0.4 on 2018-05-25 12:57

from django.db import migrations, models
import interventi.models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0009_auto_20180426_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervento',
            name='data_chiusura',
            field=models.DateField(validators=[interventi.models.valida_data_chiusura]),
        ),
        migrations.AlterField(
            model_name='intervento',
            name='data_richiesta',
            field=models.DateField(validators=[interventi.models.valida_data_richiesta]),
        ),
    ]
